@startuml
'https://plantuml.com/class-diagram


interface ScoreCalculation{
+double calculateScore(double distance)
}
class WalkScoreCalculation{
+calculateScore(double distance)
}
class TransitScoreCalculation{
+calculateScore(double distance)
}
class WalkScoreDataAccessObject {
+ assignScore(double distance)
}
WalkScoreCalculation ..|> ScoreCalculation
TransitScoreCalculation ..|> ScoreCalculation
WalkScoreDataAccessObject --> WalkScoreCalculation


@enduml